FROM node:18.18.2-alpine as builder

WORKDIR /app

COPY package*.json yarn.lock ./

RUN yarn

COPY . .

RUN yarn build

FROM node:18.18.2-alpine

WORKDIR /app

COPY --from=builder /app/build ./build
COPY package.json yarn.lock ./

RUN yarn install

CMD ["node" "./build/index.js"]